channel_sources:
  - conda-forge,phenix-project
channel_targets:
  - cctbx-dev main
c_compiler_version:
  - '13' #  [linux]
  - '18' #  [osx]
cxx_compiler_version:
  - '13' #  [linux]
  - '18' #  [osx]
