channel_sources:
  - conda-forge,phenix-project
channel_targets:
  - cctbx-dev main
libboost_devel:
  - '1.88'
libboost_python_devel:
  - '1.88'
c_compiler_version:  # [unix]
  - '14'  # [linux]
  - '19'  # [osx]
cxx_compiler_version:  # [unix]
  - '14'  # [linux]
  - '19'  # [osx]
