channel_sources:
  - cctbx202211,conda-forge,phenix-project
channel_targets:
  - cctbx-dev main
c_compiler_version:            # [osx]
  - 13                         # [osx and x86_64]
  - 14                         # [arm64]
cxx_compiler_version:          # [osx]
  - 13                         # [osx and x86_64]
  - 14                         # [arm64]
hdf5:
  - 1.12.2
c_stdlib_version:              # [osx and x86_64]
  - "10.9"                     # [osx and x86_64]
MACOSX_DEPLOYMENT_TARGET:      # [osx and x86_64]
  - "10.9"                     # [osx and x86_64]
MACOSX_SDK_VERSION:            # [osx and x86_64]
  - "10.9"                     # [osx and x86_64]
libcxx:                        # [osx and x86_64]
  - 16.0.6                     # [osx and x86_64]
libtiff:
  - 4.4
llvm_openmp:                   # [osx]
  - 13                         # [osx and x86_64]
  - 14                         # [arm64]
msgpack_c:
  - 3
python:
  - 3.7.* *_cpython            # [x86_64]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
python_impl:
  - cpython                    # [x86_64]
  - cpython
  - cpython
  - cpython
numpy:
  - 1.20                       # [x86_64]
  - 1.20
  - 1.20
  - 1.21
