channel_sources:
  - cctbx202211,conda-forge,phenix-project
channel_targets:
  - cctbx-dev main
c_compiler_version:            # [osx]
  - 13                         # [osx and x86_64]
  - 14                         # [arm64]
cxx_compiler_version:          # [osx]
  - 13                         # [osx and x86_64]
  - 14                         # [arm64]
libtiff:
  - 4.4
llvm_openmp:                   # [osx]
  - 13                         # [osx and x86_64]
  - 14                         # [arm64]
python:
  - 3.7.* *_cpython            # [x86_64]
  - 3.8.* *_cpython
  - 3.9.* *_cpython
  - 3.10.* *_cpython
python_impl:
  - cpython                    # [x86_64]
  - cpython
  - cpython
  - cpython
numpy:
  - 1.20                       # [x86_64]
  - 1.20
  - 1.20
  - 1.21
