{% set version = "dev.5515" %}

package:
  name: phenix
  version: {{ version }}

source:
  url: https://artprodcus3.artifacts.visualstudio.com/Aa21b64c7-c136-4a25-ab50-eb9ba3fa4296/f0ee1b2f-77b3-4fa6-a2c5-97101b71b939/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3BoZW5peC1yZWxlYXNlL3Byb2plY3RJZC9mMGVlMWIyZi03N2IzLTRmYTYtYTJjNS05NzEwMWI3MWI5MzkvYnVpbGRJZC8xMDI1MS9hcnRpZmFjdE5hbWUvcGhlbml40/content?format=file&subPath=/phenix.enc  # [unix]
  url: https://artprodcus3.artifacts.visualstudio.com/Aa21b64c7-c136-4a25-ab50-eb9ba3fa4296/f0ee1b2f-77b3-4fa6-a2c5-97101b71b939/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3BoZW5peC1yZWxlYXNlL3Byb2plY3RJZC9mMGVlMWIyZi03N2IzLTRmYTYtYTJjNS05NzEwMWI3MWI5MzkvYnVpbGRJZC8xMDI1MS9hcnRpZmFjdE5hbWUvcGhlbml40/content?format=file&subPath=/phenix.enc  # [win]

build:
  number: 0
  skip_compile_pyc:
    - "*/*.py"
  preserve_egg_dir: true
  script_env:
    - TARBALL_PASSWORD

outputs:
  - name: phenix
    script: build-pkg.sh  # [unix]
    script: build-pkg.bat  # [win]
    requirements:
      build:
        - python                                # [build_platform != target_platform]
        - cross-python_{{ target_platform }}    # [build_platform != target_platform]
        - numpy                                 # [build_platform != target_platform]
        - {{ compiler('c') }}
        - {{ stdlib("c") }}
        - {{ compiler('cxx') }}
        - git                                   # [win]
        - gnuconfig                             # [unix]
        - m2-tar                                # [win]
        - m2-xz                                 # [win]
        - {{ cdt('libselinux') }}               # [linux]
        - {{ cdt('libxdamage') }}               # [linux]
        - {{ cdt('libxext') }}                  # [linux]
        - {{ cdt('libxxf86vm') }}               # [linux]
        - {{ cdt('mesa-libgl-devel') }}         # [linux]
        - {{ cdt('mesa-dri-drivers') }}         # [linux]
      host:
        - libboost-python-devel
        - libboost-devel
        - eigen
        - future
        - libglu                                # [linux]
        - numpy
        - pip
        - python
        - python.app                            # [osx]
        - scons
        - setuptools
        - six
        - xorg-libxfixes                        # [linux]
        - zlib

        - hdf5
        - libtiff
        - pybind11

      run:
        - biopython
        - flask
        - future
        - ipython
        - {{ pin_compatible('libglu') }}        # [linux]
        - libsvm
        - matplotlib-base
        - mrcfile
        - {{ pin_compatible('numpy') }}
        - onedep_api
        - pillow
        - psutil
        - py2app                                # [osx]
        - pyopengl
        - pyrtf
        - pyside2                               # [py<312]
        - python
        - python.app                            # [osx]
        - pyzmq
        - qt-webengine
        - rdkit
        - reportlab
        - requests
        - restraintlib
        - scipy
        - six
        - websockets
        - wxpython

        # phasertng
        - bokeh
        - networkx
        - pyvis
    test:
      imports:
        - scitbx.array_family.flex
        - gltbx.gl  # [not win]
        - gltbx.glu  # [not win]
      commands:
        - libtbx.show_commands
        - pip check
        - mkdir test; cd test; libtbx.run_tests_parallel module=cctbx module=libtbx module=scitbx nproc=4  # [not win]
        - mkdir test && cd test && libtbx.run_tests_parallel module=cctbx module=libtbx module=scitbx nproc=4  # [win]
      requires:
        - pip

about:
  home: https://github.com/cctbx/cctbx_project
  license: BSD-3-Clause-LBNL AND BSD-3-Clause AND BSL-1.0 AND LGPL-2.0-only AND LGPL-2.1-only AND LGPL-3.0-only AND MIT AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
  license_family: Other
  license_file:
    - ./licenses/LICENSE.txt
    - ./licenses/Boost_LICENSE_1_0.txt
    - ./licenses/bsd_3_clause.txt
    - ./licenses/gpl-3.0.txt
    - ./licenses/lgpl-2.0.txt
    - ./licenses/lgpl-2.1.txt
    - ./licenses/lgpl-3.0.txt
    - ./licenses/mit.txt
    - ./licenses/wxWindows_3.1.txt

  summary: The Computational Crystallography Toolbox
  description: |
    The Computational Crystallography Toolbox (cctbx) is being developed
    as the open source component of the Phenix system. The goal of the
    Phenix project is to advance automation of macromolecular structure
    determination. Phenix depends on the cctbx, but not vice versa. This
    hierarchical approach enforces a clean design as a reusable library.
    The cctbx is therefore also useful for small-molecule crystallography
    and even general scientific applications.
  doc_url: https://cctbx.github.io/
  dev_url: https://github.com/cctbx/cctbx_project

extra:
  recipe-maintainers:
    - bkpoon
    - phyy-nx
  feedstock-name: phenix
