{% set version = "1.21rc1.4973" %}

package:
  name: phenix
  version: {{ version }}

source:
  url: https://artprodcus3.artifacts.visualstudio.com/Aa21b64c7-c136-4a25-ab50-eb9ba3fa4296/f0ee1b2f-77b3-4fa6-a2c5-97101b71b939/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3BoZW5peC1yZWxlYXNlL3Byb2plY3RJZC9mMGVlMWIyZi03N2IzLTRmYTYtYTJjNS05NzEwMWI3MWI5MzkvYnVpbGRJZC81NDYyL2FydGlmYWN0TmFtZS9waGVuaXg1/content?format=file&subPath=/phenix.enc  # [unix]
  url: https://artprodcus3.artifacts.visualstudio.com/Aa21b64c7-c136-4a25-ab50-eb9ba3fa4296/f0ee1b2f-77b3-4fa6-a2c5-97101b71b939/_apis/artifact/cGlwZWxpbmVhcnRpZmFjdDovL3BoZW5peC1yZWxlYXNlL3Byb2plY3RJZC9mMGVlMWIyZi03N2IzLTRmYTYtYTJjNS05NzEwMWI3MWI5MzkvYnVpbGRJZC81NDYyL2FydGlmYWN0TmFtZS9waGVuaXg1/content?format=file&subPath=/phenix.enc  # [win]

build:
  number: 0
  skip: true  # [win]
  skip_compile_pyc:
    - "*/*.py"
  preserve_egg_dir: true
  script_env:
    - TARBALL_PASSWORD

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - future                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - six                                    # [build_platform != target_platform]
    - gnuconfig  # [unix]
    - git  # [win]
    - m2-tar  # [win]
    - m2-xz  # [win]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
    - {{ cdt('libselinux') }}  # [linux]
    - {{ cdt('libxdamage') }}  # [linux]
    - {{ cdt('libxxf86vm') }}  # [linux]
    - {{ cdt('libxext') }}     # [linux]
  host:
    - boost =1.74  # [not arm64]
    - boost =1.78  # [arm64]
    - boost-cpp =1.74  # [not arm64]
    - boost-cpp =1.78  # [arm64]
    - eigen
    - future
    - libglu  # [linux]
    - numpy
    - pip
    - python
    - python.app  # [osx]
    - scons
    - setuptools
    - six
    - xorg-libxfixes  # [linux]

    - hdf5
    - libtiff
    - msgpack-c
    - pybind11

outputs:
  - name: phenix
    requirements:
      run:
        - biopython
        - {{ pin_compatible('boost') }}
        - boost-cpp
        - future
        - {{ pin_compatible('libglu') }}  # [linux]
        - libsvm
        - matplotlib-base
        - mrcfile
        - {{ pin_compatible('numpy') }}
        - pillow
        - psutil
        - python
        - python.app  # [osx]
        - reportlab
        - requests
        - scipy
        - six

        # - amber_phenix  # [not win and x86_64]
        - flask
        - gdk-pixbuf  # [linux and not py==39]
        - onedep_api
        - pyrtf
        - rdkit
        - wxpython
        - pyside2  # [x86_64]
        - restraintlib

        # pathwalker
        - absl-py
        - pip
        - protobuf

        # phasertng
        - bokeh
        - networkx

        # dxtbx
        - h5py
        - hdf5
        - hdf5plugin
        - libtiff
        - pint
        - procrunner
        - pybind11

        # dials
        - colorlog
        - msgpack-c
        - msgpack-python
        - orderedset
        - scikit-learn
        - tabulate
        - tqdm
    test:
      imports:
        - scitbx.array_family.flex
        - gltbx.gl  # [not (win and py==39)]
        - gltbx.glu  # [not (win and py==39)]
      commands:
        - libtbx.show_commands
        - pip check
      requires:
        - pip

about:
  home: https://github.com/cctbx/cctbx_project
  license: BSD-3-Clause-LBNL AND BSD-3-Clause AND BSL-1.0 AND LGPL-2.0-only AND LGPL-2.1-only AND LGPL-3.0-only AND MIT AND LGPL-2.0-or-later WITH WxWindows-exception-3.1
  license_family: Other
  license_file:
    - ./licenses/LICENSE.txt
    - ./licenses/Boost_LICENSE_1_0.txt
    - ./licenses/bsd_3_clause.txt
    - ./licenses/gpl-3.0.txt
    - ./licenses/lgpl-2.0.txt
    - ./licenses/lgpl-2.1.txt
    - ./licenses/lgpl-3.0.txt
    - ./licenses/mit.txt
    - ./licenses/wxWindows_3.1.txt

  summary: The Computational Crystallography Toolbox
  description: |
    The Computational Crystallography Toolbox (cctbx) is being developed
    as the open source component of the Phenix system. The goal of the
    Phenix project is to advance automation of macromolecular structure
    determination. Phenix depends on the cctbx, but not vice versa. This
    hierarchical approach enforces a clean design as a reusable library.
    The cctbx is therefore also useful for small-molecule crystallography
    and even general scientific applications.
  doc_url: https://cctbx.github.io/
  dev_url: https://github.com/cctbx/cctbx_project

extra:
  recipe-maintainers:
    - bkpoon
    - phyy-nx
