github:
  user_or_org: phenix-project
  repo_name: phenix-feedstock
  branch_name: main
  tooling_branch_name: main
channels:
  targets:
    - [cctbx-dev]
secrets:
  - TARBALL_PASSWORD

channel_priority: flexible
azure:
  user_or_org: phenix-release
  project_name: feedstock-builds
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
test: native
upload_on_branch: upload
conda_build:
  pkg_format: '2'
