github:
  user_or_org: phenix-project
  repo_name: phenix-feedstock
channels:
  sources:
    - cctbx202112
    - conda-forge
    - dacase
    - phenix-project
    - defaults
  targets:
    - [cctbx-dev, main]
secrets:
  - TARBALL_PASSWORD

#channel_priority: flexible
azure:
  user_or_org: phenix-release
  project_name: feedstock-builds
  store_build_artifacts: true
build_platform:
  osx_arm64: osx_64
test_on_native_only: true
upload_on_branch: upload
build_with_mambabuild: False
