github:
  user_or_org: phenix-project
  repo_name: phenix-feedstock
  branch_name: main
  tooling_branch_name: main
secrets:
  - TARBALL_PASSWORD

channel_priority: flexible
azure:
  user_or_org: phenix-release
  project_name: feedstock-builds
  free_disk_space: true
  store_build_artifacts: true
  settings_win:
    variables:
      CONDA_BLD_PATH: C:\\Miniconda\\envs\\
build_platform:
  osx_arm64: osx_64
test: native
upload_on_branch: upload
conda_build:
  pkg_format: '2'
  zstd_compression_level: 22
